Feat/auth : 소셜 로그인 추가 및 페이지 이동
seokwon27/takkom pull request #19
Opened 2024-10-29 12:05 UTC by leeyeram84

## 🔥 작업 내용

- 소셜 로그인 추가 (구글, 카카오)
- 로그인 시 페이지 이동
- 기타 소소한 디테일 수정

## 📸 스크린샷

- 구글 로그인
<img src = "https://media.discordapp.net/attachments/1244516648866680885/1300792364712988712/2024-10-299.00.55-ezgif.com-video-to-gif-converter.gif?ex=672220cb&is=6720cf4b&hm=e6e83b0f321da62e5c575216bc516cb6b4c4642812905c046395982026b5d25e&=&width=1100&height=688">

- 카카오 로그인
<img src = "https://media.discordapp.net/attachments/1244516648866680885/1300792589028425739/2024-10-299.01.44-ezgif.com-video-to-gif-converter.gif?ex=67222100&is=6720cf80&hm=9429d813366674d42e02c48a521d20a53b34b63f0bf08219bf929b0c2a1d6494&=&width=1100&height=688">

## 💁🏻‍♀️ 테스트 체크리스트

- 소셜 로그인 : 구글과 카카오에서 제대로 로그인창이 받아와지고 로그인 후 메인 페이지로 이동 확인
- 로그인 시 헬퍼텍스트가 랜더링 되는 오류가 있었지만 수정하여 지금은 바로 넘어가짐
- 로그인 후 유져 데이터도 잘 불러와짐

## 👍 참고 사항

- 관련된 이슈나 참고할 사항을 적어주세요!
-

2024-10-29 12:15 UTC, joycie416 requested changes
supabase client 부분 수정 요청드립니다~

2024-10-29 12:15 UTC, joycie416 commented on src/components/auth/SignIn.tsx
>  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string;
supabase-js에서 createClient() 불러오지 마시고 client.ts에서 browserClient를 사용하거나 server.ts에서 createClient() 바로 가져와서 사용하면 됩니다. client.ts, server.ts에서 supabase url, key 모두 적용되어 있습니다.

2024-10-29 12:15 UTC, joycie416 commented on src/components/auth/SignOut.tsx
> +const supabase = createClient(supabaseUrl, supabaseKey);
마찬가지로 supabase-js에서 createClient() 불러오지 마시고 client.ts에서 browserClient를 사용하거나 server.ts에서 createClient() 바로 가져와서 사용하면 됩니다.

2024-10-29 12:15 UTC, joycie416 commented on src/components/auth/SignUp.tsx
>  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string;
마찬가지로 supabase-js에서 createClient() 불러오지 마시고 client.ts에서 browserClient를 사용하거나 server.ts에서 createClient() 바로 가져와서 사용하면 됩니다.

2024-10-29 12:16 UTC, stopbrother approved these changes
고생하셧습니다

2024-10-30 02:19 UTC, seokwon27 approved these changes
고생하셨습니다

2024-10-30 02:27 UTC, leeyeram84 commented on src/components/auth/SignUp.tsx
>  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string;
수정했습니다!

2024-10-30 03:54 UTC, joycie416 approved these changes
수정 감사합니다.

2024-10-30 03:54 UTC, Sehee-Jang approved these changes
확인했습니다

2024-10-30 03:54 UTC, merged