Feat/auth : 로그인 상태 유지 및 소셜 로그인 리다이랙트 설정
seokwon27/takkom pull request #25
Opened 2024-10-30 12:08 UTC by leeyeram84

## 🔥 작업 내용

- 로그인 후 로그인 상태 유지 추가
- 환경별 소셜 로그인 리다이렉트 설정을 위해 환경변수 추가

## 📸 스크린샷

- 변경내용 스크린샷을 추가해주세요!

## 💁🏻‍♀️ 테스트 체크리스트

- 테스트했던 내용을 적어주세요!
-

## 👍 참고 사항

- 환경 변수는 버셀에서의 별도 설정 필요
-

2024-10-30 12:09 UTC, seokwon27 approved these changes
확인했습니다

2024-10-30 13:36 UTC, joycie416 requested changes
카멜 케이스 오타 수정 요청드려용

2024-10-30 13:36 UTC, joycie416 commented on src/components/auth/SignIn.tsx
> +  const [issignIn, setIsSignIn] = useState(false);
`isSignIn` 카멜 케이스 오타..!

2024-10-30 13:36 UTC, joycie416 commented on src/components/auth/SignUp.tsx
> +  const [issignIn, setIsSignIn] = useState(false);
`isSignIn` 카멜 케이스 오타!

2024-10-31 00:50 UTC, stopbrother approved these changes
乃 수정사항 반영 후 머지

2024-10-31 03:20 UTC, joycie416 approved these changes
믿습니다 예람님!

2024-10-31 03:20 UTC, merged