개발 브랜치 PR
seokwon27/takkom pull request #9
Opened 2024-10-25 06:57 UTC by seokwon27

## 🔥 작업 내용

- 작업 내용을 적어주세요!
-

## 💁🏻‍♀️ 테스트 체크리스트

- 테스트했던 내용을 적어주세요!
-

## 👍 참고 사항

- 관련된 이슈나 참고할 사항을 적어주세요!
-

2024-10-25 08:05 UTC, CaesiumY requested changes
오늘 안으로 다 수정하시죠...ㅎ

![image](https://github.com/user-attachments/assets/375d0dec-b784-4e4c-8f59-ed0a3f20f724)

2024-10-25 08:05 UTC, CaesiumY commented on .eslintrc.json
> +    "@typescript-eslint/no-empty-object-type": "off"
이걸 넣게 되신 이유가 궁금합니다! eslint 설정은 어지간하면 바꾸지 않거든용

2024-10-25 08:05 UTC, CaesiumY commented on package.json
> +    "gen": "^2.0.1",
이거랑 `types` 패키지는 사용 안 하니 삭제해주시죠!

2024-10-25 08:05 UTC, CaesiumY commented on package.json
> +    "supabase": "^1.207.9",
이 supabase 패키지도 현재 유저한테 필요한 게 아니라 우리가 타입을 자동 생성하기 위한 cli를 실행하기 위해 필요한 패키지잖아요? 그러니 devDependency에 들어갈 수 있도록 `-D` 옵션을 줘서 새로 설치하시죠! 그리고 현재 이 버전도 최신이 아니기에 최신 버전으로 업데이트 해주세요!!

2024-10-25 08:05 UTC, CaesiumY commented on src/app/(auth)/signin/page.tsx
> +    <div>
시맨틱 웹을 위해 `section` 태그는 어떠신가요~~~

2024-10-25 08:05 UTC, CaesiumY commented on src/app/globals.css
> +    box-sizing: border-box;
이거 기본 값인 걸로 알고 있는데 굳이 다시 추가해준 이유가 있을까용??

2024-10-25 08:05 UTC, CaesiumY commented on src/app/layout.tsx
> +  title: "따꼼",
타이틀에도 템플릿을 만들어줄 수 있어요! 한 번 찾아보시죠!
https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

2024-10-25 08:05 UTC, CaesiumY commented on src/app/layout.tsx
>      <html lang="en">
우리 사이트 영어인가용?????

2024-10-25 08:05 UTC, CaesiumY commented on src/app/page.tsx
> +const Home = () => {
페이지 컴포넌트는 컴포넌트 접미사에 `Page`를 넣어주시면 좋습니당. 그러면 여기는 `HomePage` 가 되겠죠?

2024-10-25 08:05 UTC, CaesiumY commented on src/app/search/page.tsx
> +const page = async () => {
페이지 컴포넌트 이름 빼먹지 말아주세요!

2024-10-25 08:05 UTC, CaesiumY commented on src/app/search/page.tsx
> +  const brtcObj = await getBrtcCd();
brtc가 무엇인가요? 약어는 사용하지 않는 게 베스트이지만 만약에 꼭 필요하다면 팀원들이 알아들을 수 있도록 주석이 필요합니당

2024-10-25 08:05 UTC, CaesiumY commented on src/app/search/page.tsx
> +  const brtcObj = await getBrtcCd();
만약 용어를 바꾸는 게 힘들다면, 해당 함수 내부에서 단어에 대한 설명을 주석으로 추가해주는 게 좋아보이네용

2024-10-25 08:05 UTC, CaesiumY commented on src/app/vaccineinfo/page.tsx
> +  const serverClinet = createClient();
사용하지 않는 코드 발견~~

2024-10-25 08:05 UTC, CaesiumY commented on src/components/VaccinateRecord.tsx
> +      {data?.map((vaccine) => (
data 길이가 0일 경우에 '데이터가 존재하지 않습니다' 같은 인디케이터를 넣어주면 좋을 거 같아용

2024-10-25 08:05 UTC, CaesiumY commented on src/components/auth/authsignup.tsx
컴포넌트 이름은 파스칼 케이스로 통일해주세요~~
이름을 대문자로 바꾸고 싶으면 aaa -> bbb -> AAA 로 바꿔주셔야 깃이 트래킹할 수 있어요!

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +const BRTC = "시/도";
이런 상수 부분은 `contants.ts` 파일로 내보내시는 게 좋을 거 같요

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +    let newParams = `?brtcCd=${params.brtcCd}&sggCd=${params.sggCd}`;
https://developer.mozilla.org/ko/docs/Web/API/URL/searchParams

SearchParams 객체를 활용해보세요!!

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +    let newParams = `?brtcCd=${params.brtcCd}&sggCd=${params.sggCd}`;
```ts
const queryString = new URLSearchParams({ brtcCd })

sggCdd && queryString.set('sggCdd', sggCdd)

```

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
인라인으로 가져오는 함수는 이미 타이핑이 되어 있기 때문에 따로 매개변수에 타입을 지정해주지 않아도 됩니다!

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +            setAddr(e.target.value.trim());
공백 제거는 마지막에 제출할 때 해주시는 게 좋아요!

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +            e.preventDefault();
버튼 눌렀을 때 form의 submit 이벤트를 막으시려는 거 같은데 이 방법으로 하시는 게 아니라, button에 `type='button'` 을 주는 걸로 막으셔야 해용

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +      {children}
레이아웃이나 고차 컴포넌트나 공용 컴포넌트가 아닌 이상 `children`은 쓸 일이 없어용

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +              {Object.entries(regionInfo.get(brtc[0]) ?? {})?.map((item) => (
딱 코드를 보면... 위화감이 생기지 않나요...?? 그러면 고쳐야 합니다~~

2024-10-25 08:05 UTC, CaesiumY commented on src/components/hospital/SearchForm.tsx
> +            const sggObj = regionInfo.get(brtc[0]) ?? { "시/군/구": SGG };
이쪽에 인라인으로 다 넣지 말고, 초기화 함수를 하나 만들어주는 건 어떨까요? 그러면 더 이곳을 깔끔하게 만들 수 있을 거 같아요!

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeFilter.tsx
> +  const subAgeGroup = useMultiStore((state) => state.subAgeGroup);
store 이름 변경이 필요할 거 같아요. 지금은 어떤 데이터를 다루는지 알 수 없는 네이밍이네용

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeFilter.tsx
> +  const subAgeGroup = useMultiStore((state) => state.subAgeGroup);
`const { subAgeGroup, age, setAge } = useMultiStore()`

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeFilter.tsx
> +              key={index}
`key`에 `index`는 리액트 초보자들이 많이 범하는 실수입니당

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeFilter.tsx
> +        {subAgeGroup.map((el, index) => {
`el`이 뭐죠...??

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeGroup.tsx
> +      <div>{`선택된 연령 그룹 : ${ageGroup}`}</div>
텍스트가 바로 들어와있으니 `p` 태그는 어떨까요?

2024-10-25 08:05 UTC, CaesiumY commented on src/components/vaccineinfo/AgeGroup.tsx
> +        <div className="p-2 " onClick={() => setAgeGroup("신생아")}>
요부분 계속 반복되는데 자그마한 컴포넌트로 분리할 수 있지 않을까요?

다른 컴포넌트에서 쓰이지 않는 이곳에서만 쓰이는 코드라 우려되신다면 지금 이 파일 아래에 새 컴포넌트를 선언해서 두 개의 컴포넌트가 한 파일 내에 존재하도록 하면 됩니당

2024-10-25 08:05 UTC, CaesiumY commented on src/query/useVaccinationQuery.ts
그냥 `vaccine` 으로 통일하시죠!!

2024-10-25 08:05 UTC, CaesiumY commented on src/types/hospital.ts
> +export type RegtionItem = {
오타 발견!!!

2024-10-25 08:05 UTC, CaesiumY commented on src/types/hospital.ts
> +export type HopsitalItem = {
여기 주석 넣어서 각 필드마다 어떤 걸 뜻하는지 설명이 필요해보입니다...ㅠ

2024-10-25 08:05 UTC, CaesiumY commented on src/utils/globalStore.ts
어떤 store인지 명확한 이름을 지어주세용~

2024-10-25 08:05 UTC, CaesiumY commented on src/utils/hospital/server-action.ts
파일 명이랑 주소 변경이 필요합니다!!

2024-10-25 08:05 UTC, CaesiumY commented on src/utils/hospital/server-action.ts
> +const serviceKey = process.env.NEXT_PUBLIC_HOSPITAL_KEY_DEC as string;
뭔가 숨겨야 하는 키 같으니 prefix 같은 `NEXT_PUBLIC`은 빼시죠!

2024-10-25 08:11 UTC, joycie416 commented on .eslintrc.json
> +    "@typescript-eslint/no-empty-object-type": "off"
shadcn에서 empty object type을 사용하는 것 같습니다. 그래서 해당 빌드 에러를 없애기 위해 추가했습니다.

2024-10-25 08:38 UTC, joycie416 commented on src/components/hospital/SearchForm.tsx
> +          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
제거했습니다.

2024-10-27 15:11 UTC, joycie416 commented on src/components/hospital/SearchForm.tsx
> +    let newParams = `?brtcCd=${params.brtcCd}&sggCd=${params.sggCd}`;
수정했습니다.

2024-10-28 03:37 UTC, leeyeram84 approved these changes

2024-10-28 03:45 UTC, seokwon27 commented on src/app/layout.tsx
>      <html lang="en">
수정했습니다

2024-10-28 03:49 UTC, seokwon27 commented on src/app/page.tsx
> +const Home = () => {
수정했습니다

2024-10-28 03:50 UTC, seokwon27 commented on src/app/vaccineinfo/page.tsx
> +  const serverClinet = createClient();
제거했습니다~

2024-10-28 03:51 UTC, stopbrother commented on src/components/VaccinateRecord.tsx
> +      {data?.map((vaccine) => (
`if (!data) <div>데이터가 존재하지 않습니다.</div>;`

추가 했습니다

2024-10-28 03:52 UTC, stopbrother commented on src/query/useVaccinationQuery.ts
useVaccineRecordQuery.ts로 수정했습니다

2024-10-28 03:52 UTC, seokwon27 commented on src/utils/globalStore.ts
ageGroupStore.ts 로 변경하였습니다.

2024-10-28 13:18 UTC, joycie416 approved these changes
피드백 반영했습니다.

2024-10-29 07:18 UTC, seokwon27 commented on src/app/globals.css
> +    box-sizing: border-box;
프로젝트 생성과 동시에 생긴 듯합니다. globallCss는 건드리지 않았던거 같은데...

2024-11-01 08:00 UTC, CaesiumY requested changes

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/register/steps/RegisterStep1.tsx
> +  const uploadImage = async (file: File): Promise<string | null> => {
커스텀 훅으로 분리하면 더 보기 좋을 거 같아용

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/register/steps/RegisterStep1.tsx
> +                    onChange={(e) => setSelectedImage(e.target.files?.[0] ?? undefined)}
`e.target.files[0]` 이 존재할 때 setState 함수를 호출하는 건 어떨까요?

2024-11-01 08:00 UTC, CaesiumY commented on src/api/hospitalApi.ts
> +      return data;
early return 기법을 사용해보세요!

2024-11-01 08:00 UTC, CaesiumY commented on src/api/userApi.ts
> +    console.error(error);
에러 나면 콘솔에 찍어주기만 하는 게 아니라 `throw new Error()` 도 해주세용

2024-11-01 08:00 UTC, CaesiumY commented on src/api/vaccineApi.ts
> +export interface vaccineSchedule extends Omit<Tables<'vaccine'>, 'vaccinae_date' | 'duration'> {
타입 파일로 분리하는 게 좋아보여용

2024-11-01 08:00 UTC, CaesiumY commented on src/api/vaccineApi.ts
> +    } else {
else 를 빼고 새로운 if문 조건을 넣는 걸로 하시죠~

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/[id]/edit/page.tsx
> +            <div>전체</div>
글자만 들어있다면 `p` 태그는 어떠실런지요

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/[id]/edit/page.tsx
> +        <CheckboxForm child_id={params.id} />
`child_id` 가 현재 `snake_case`네요. 자바스크립트에서는 `camelCase` 를 쓰시는 게 좋습니다!

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/page.tsx
> +"use client";
page는 서버 컴포넌트로 유지하시죠!

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/register/page.tsx
> +"use client";
page 컴포넌트는 서버 컴포넌트로 유지(2)

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/register/steps/RegisterStep1.tsx
> +      name: childInfo.name || "",
`??` 로 바꿔주시는 게 좋습니당

2024-11-01 08:00 UTC, CaesiumY commented on src/app/child/register/steps/RegisterStep2.tsx
> +    const fetchChildData = async () => {
tanstack 쿼리로 마이그레이션 해주세요!

2024-11-01 08:00 UTC, CaesiumY commented on src/app/layout.tsx
> +    <html lang="kor">
언어 표시는 `ko` 로!

2024-11-01 08:00 UTC, CaesiumY commented on src/components/auth/SignIn.tsx
> +              <FormDescription className={form.formState.errors.password ? "text-red-500" : "text-gray-600"}>
https://ui.shadcn.com/docs/components/form#done

`FormMessage`로 변경하시죠!

2024-11-01 08:00 UTC, CaesiumY commented on src/components/auth/SignUp.tsx
> +  const [issignIn, setIsSignIn] = useState(false);
사용하지 않는 상태는 지워주시오

2024-11-01 08:00 UTC, CaesiumY commented on src/components/child/RegisterButton.tsx
> +  return <button onClick={handleRegisterClick}>우리아이 등록하기</button>;
Link 컴포넌트 안에 버튼 태그를 넣는 방식으로 구현합시당

2024-11-01 08:00 UTC, CaesiumY commented on src/components/child/RegisterForm.tsx
> +      {step === 1 ? (
`&&` 연산자로 조건부 렌더링 해주시는 게 더 보기 좋을 거 같아요

2024-11-07 02:01 UTC, merged